nunocoracao/blowfish

- layouts/partials/article-link.html
Currently the images are displayed at their full resolution. Those images could be very large, but end up being displayed as 300px wide. This changes that by resizing those images to a more suitable size.
> Resize images displayed in article-link.html

- exampleSite/content/users.md
Small change, the link under the Users page redirects to what I believe was a previous branch that is now non-existent
Also, added my personal site to the list.
> fix: broken link and add: user website

- data/sharing.json
- layouts/partials/sharing-links.html
This PR changes this by grouping the links within an object key: `Site.Data.sharing.links`. This means that sites can provide their own `data/sharing.json` file and overwrite the `links` key, to provide links of their own links.
Without the key, any custom links in `data/sharing.json` are appended, due to Hugo de-duping keys (not files).
> Allow overwriting of sharing links

- assets/css/compiled/main.css
- layouts/partials/icon.html
- layouts/partials/sharing-links.html
The current sharing icons are currently anchored to the bottom with uneven visual padding around this. The PR changes them to be centred.
Current:
With PR:
> Improve visuals of sharing links

- i18n/bn.yaml
- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/he.yaml
- i18n/hr.yaml
- i18n/hu.yaml
- i18n/id.yaml
- i18n/it.yaml
- i18n/ja.yaml
- i18n/pl.yaml
- i18n/pt-BR.yaml
- i18n/pt-PT.yaml
- i18n/ro.yaml
- i18n/ru.yaml
- i18n/tr.yaml
- i18n/zh-CN.yaml
- i18n/zh-TW.yaml
- layouts/partials/series-closed.html
- layouts/partials/series.html
Replacing static text for `articles series` with entries in i18n. 
I'm using English for all i18n resources except Spanish (the only other language I know), because I don't like automatic translations as I can't verify if it's a good one. I know is not ideal, but other languages will keep showing as they were before this change
> ♻️ Add i18n for article series

- layouts/partials/article-link-card.html
- layouts/partials/article-link.html
Currently, the image is resized to be 600px, which will work for most images, but causes issues for images which have very wide aspect ratios. This change updates the partials to use a `Fill` with an appropriate bounding box, rather than a simple resize. The bounding box chosen roughly matches what the displayed aspect ratio ends up at.
You can read more about Fill [here](https://gohugo.io/content-management/image-processing/#fill).
To show an example, here's the current behavior for a wide image:
...and with this PR:
> 💄 Improve resizing for article thumbnails

- assets/css/compiled/main.css
- layouts/partials/recent-articles.html
Currently the items include some inner padding, which means that the items have some leading spacing on the left/right which don't align with the keyline.
This PR updates this to use a grid, with a fixed number of columns depending on the screen size.
Before: (notice that the item doesn't align with the 'recent' word)
With PR:
> 💄 Use grid rather than flexbox for recent articles

- layouts/partials/header/fixed.html
closes #363 
i just changed the height of the header to be automatic
how it was before my change:
how it is after my change:
> :bug: Fix header with disabled logo on mobile

- config/_default/config.toml
- exampleSite/content/users/index.md
- i18n/cs.yaml
- layouts/_default/baseof.html
- layouts/partials/series-closed.html
- layouts/partials/series.html
As I write in czech, I noticed that when I use UTF-8 encoded characters (š,ř,ž etc.) in a series name, it won't associate it with any articles. The problem is in the _urlize_ function in the _series.html_ and _series-closed.html_ files.
`{{ range $post := sort (index .Site.Taxonomies.series (index .Params.series 0 | urlize)) "Params.series_order" }}`
Besides converting the name lowercase and replacing spaces with hyphens it also changes non ASCII characters to URL friendly format (Čeština -> %C4%8Ce%C5%A1tina). That leads to the inability of the next function: `{{ if eq $post.Permalink $.Page.Permalink }}` to match series names with corresponding posts.
So I changed the code so that now it only converts the name to lowercase and replaces spaces with hyphens.
I also added my personal …
> :sparkles: Support for UTF-8 encoded series names; small updates

- layouts/partials/header/basic.html
This was caused by an extra space before an enquoted identifier, causing the i18n lookup to fail.
> :adhesive_bandage: :wheelchair: Fix missing title attribute from search button

- exampleSite/content/docs/getting-started/index.md
- layouts/partials/header/basic.html
Adds support for a configurable `subnavigation` menu below the header as shown in the attached screenshots. Menu is configured pretty much in the same way as the others, by editing `menus.en.yml`
> ✨ Add support for subnavigation menu

- layouts/_default/baseof.html
- layouts/partials/scroll-to-top.html
This PR simply extracts the existing "scroll to top" section of code into a dedicated partial and then calls that in place.
The problem this solves is that it allows for easier customization of the icon. Personally, I don't like the plain arrow and on my website I implemented a circular button with an arrow up (like a fab). To do so, I had to override the `baseof` partial which is tricky as it can break with future updates. Extracting it as a partial makes it easy to just dump some new html code in the `layouts/partials/scroll-to-top.html` file in my repo to integrate more nicely with the theme.
> Extract the "scroll to top" section as a partial

- layouts/_default/single.html
This is to support scenarios when custom heroStyle is specified in a single article's front-matter
> :bug: added support for heroStyle via front-matter

- exampleSite/content/docs/getting-started/index.md
Changed The Link To Blowfish's Icon Page To A Relative One So The Link Resolves Correctly On Remote Instances Such As The One Hosted At https://nunocoracao.github.io/.
> :bug: Fix Broken Icon Link

- layouts/shortcodes/alert.html
> 🐛 Icon not centered in alert shortcode

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/gallery.html
> :sparkles: shortcode gallery

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/carousel.html
Currently, if I have multiple `carousel` elements in the same page, they scroll more or less at the same time, which looks kind of bad.
This PR solves the problem by adding a pseudo-random time to each carousel to stagger them a bit, making the page look more "dynamic".
The base duration for scrolling is set to 2000 millis. On top of that, a pseudo-random number from `0` to `999` millis is added, to have random values in the `[2000, 2999]` range.
> ✨ Shortcode `carousel`: add optional parameter for scroll duration

- assets/css/compiled/main.css
- assets/css/main.css
> ✨ Mobile classes for gallery and carousel

- layouts/partials/home/card.html
This is my personal hotfix to #516 . It enforces width on the container for the image card, and replicates the content formatting for some amount of responsiveness. This is not intended as a true fix, but is potentially a start.
Remaining issue: scaling on iPad in the landscape view still spills over. Other views appear acceptable.
> Hotfixed homepage card spillover on responsive displays

- layouts/partials/head.html
This PR is a potential small seo improvement. If there is a configured `summary` in the page frontmatter, it will be used in the `<meta name="description">` tag instead. If this isn't configured, then it defaults to `Site.Params.description`
> ❇️ Use article/page configured summary ahead of default

- layouts/partials/hero/big.html
- layouts/partials/home/background.html
This change improve accessibility by:
- indicating that the background image is use for presentation only and then do not need an alt text
- add an alt text to the big hero image  defaulting to page title or to the specified "alt" param in the Page Bundle.
I've also set a fixed image ratio for the big hero image to improve performance (less page redraws).
> ♿️ Alt text management

- layouts/partials/head.html
zoom.min.js is not found when site is not in the root and baseURL is set accordingly to something like `https://website.com/test/`. Other files in the static folder work fine. Only zoom.min.js has this issue.
> 🔧 Fixed zoom.min.js library not being found if site is in a subfolder.

- layouts/shortcodes/gallery.html
Having multiple galleries in the same page makes them have the same ID (as now.UnixNano can be the same), so only the javascript of the first gallery works. This adds a unique number to the ID of each gallery so it fixes the problem.
> Fixed having multiple galleries in the same page, only works the first one

- layouts/partials/analytics/fathom.html
With the latest refactor, the site id for fathom analytics is not correctly set. This PR should fix it.
> 🐛 fix regression in fathom analytics

- layouts/_default/rss.xml
- Copyright in RSS feeds would show the "{ year }" code instead of the proper year. Also, the logic matches the one in the footer of the page.
- Changed the language code to match with the [current Hugo default RSS template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml).
- Renamed index.rss.xml to rss.xml. Previously, the template provided with blowfish would only load in the root of the site, all other sections would load the default Hugo template, which has the Copyright issue. Now the provided template loads properly everywhere in the site. Unless it was intentional that it only loads in the root?
> 🐛 Fix for wrong Copyright in RSS feeds

- assets/css/compiled/main.css
- layouts/_default/list.html
- layouts/_default/single.html
The TOC can be partially hidden by the main menu when scrolling down if that menu has a logo image. That's even visible in the Blowfish page. Just to test that it wasn't a Windows thing, I also checked on Ubuntu and same result.
I adjusted the top value so the TOC never goes that high in the page when scrolling down.
> 🎨 Fix that prevents the TOC from being covered by the main menu.

- layouts/partials/head.html
depending on the basePath, the "appearance.js" was generated in an additional subfolder (Example: set the basePath to "https://example.com/foobar/", the file was generated into "/js/foobar/appearance...js" instead of "/js/appearance...js" ).
This fixes the behaviour, the javascript resource is always generated into the target "js" folder along with all the other js files.
> Always generate appearance.js in js folder

- layouts/partials/author-extra.html
- layouts/partials/author.html
- layouts/partials/home/background.html
- layouts/partials/home/hero.html
- layouts/partials/home/profile.html
The disableImageOptimization setting now affects author images, like the rest of the images.
> 🎨 The disableImageOptimization setting now affects author images

- i18n/ko.yaml
Created a YAML file for Korean (KO) speaking users.
First time contributing to an open source project, so please let me know if made any mistakes or if you have constructive criticism for me.
**Notes/ Questions:**
1. **Line 44**, you might noticed that the text was added after `{{ .Hugo }} &amp; {{ .Theme }}`, this is intentional because it flows better in Korean that way.
2. Wanted to ask about **line 55 and 57**, the "search" that I wrote for **line 55** is a verb, the "search" written for **line 57** is a noun. Do you want me to change **line 57**?
3. Technically in **line 61** Facebook can be written as "페이스북", in the interest of keeping thing consistent, I've chosen to write it in English (still works grammatically).
> :sparkles: Korean YAML File for Blowfish

- exampleSite/content/samples/charts/index.md
- exampleSite/content/samples/diagrams-flowcharts/index.md
Good day!
Fix for broken links in samples for charts and diagrams: https://blowfish.page/samples/diagrams-flowcharts/
Thank you.
> 🐛 fix: broken links in samples

- layouts/partials/author-links.html
Added safeURL to author links so that ftp and phone links work correctly.
See Hugo documentation for more information:
https://gohugo.io/functions/safeurl/
> 🐛 Fix tel:, ftp:, etc URLs For Author Links

- .vscode/blowfish.code-snippets
- .vscode/codesnippets-doc.md
- .vscode/textmate-code-snippets.md
Not sure if you want these or not; but thought I'd share.
Here are some pseudo-opinionated code-snippets for vscode. they make using the shortcodes in blowfish a bit easier.
Alongside the shortcodes are Markdown versions of the vscode code-snippets documentation, and the textmate code-snippets documentation that vscode's implementation attempts to be compatible with.
One of the inherent downsides of the tool is there is not an 'optional' tabstop.
one is given two options with tab-iteratable parameters: 
- tab-stop-with-free-text
- tab-stop-with-a-set-list-of-values, values may not be null.
This makes it a little obtuse to enumerate all possible shortcode parameters for ease of recall.
My solution is to create a static list tabstop for optional parameters, with the options of
- a space
- a …
> add vscode code-snippets for blowfish shortcodes

- layouts/_default/sitemap.xml
- Include pages with relative externalUrl with correct URL in Sitemap
- Exclude pages with absolute externalUrl from Sitemap
- Include pages with relative externalUrl with correct URL in Sitemap
- Improve output XML (no more linebreaks and spaces)
> feat: exclude external pages from Sitemap

- exampleSite/content/users/users.json
After browsing some of the pages on the users page of the blowfish site, I have found that there was a site returning a 404. Due to this I decided to remove it to make sure that things work good.
:+1:
> Remove non-existant site (404)

- i18n/ru.yaml
I found an error in spelling and corrected it. [Check](https://advego.com/text/):
> 🎏 [i18n/ru] Removing an extra letter in a pinterest string

- layouts/partials/head.html
There is already [an if condition](https://github.com/nunocoracao/blowfish/blob/45d634f6ca698abdbfebf67e955211f090043e5b/layouts/partials/footer.html#L46) in `footer.html` that only runs the JS from the zoom library if it is enabled per-site.
This commit takes the same if condition and applies it in `head.html` as well to save a unnecessary web request to `zoom.min.js` if that is the case.
> Only send web request for zoom library if it is not disabled.

- exampleSite/content/_index.md
- layouts/partials/article-meta/basic.html
Fixes https://github.com/nunocoracao/blowfish/issues/956
> Missing pointer-cursor for tag-badge in article view

- layouts/_default/list.html
- layouts/_default/single.html
When I was creating a post, I was getting this warning:
```
WARN  .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
```
So I did as suggested and replaced the `.File.Path` using a `with` statement in the `list.html` and `single.html` files. So far, the warning hasn't popped up again.
I am not sure why this warning comes up, but I hope this will mitigate weird behavior in the future.
I noticed this warning in two issues #602 and #490
> Fix annoying `.File.Path on zero object.` warning

- exampleSite/content/users/users.json
Adds my [personal website](https://alxhslm.github.io/) to users.json so it appears on the "Users" page.
> 👤 Add website to users.json

- layouts/partials/article-link/card-related.html
- layouts/partials/article-link/card.html
- layouts/partials/article-link/simple.html
- layouts/partials/scroll-to-top.html
- layouts/partials/term-link/card.html
- layouts/partials/translations.html
- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
- layouts/shortcodes/timelineItem.html
This should mostly fix https://github.com/nunocoracao/blowfish/issues/994 and partially address https://github.com/nunocoracao/blowfish/issues/907.
- Removes most of the extraneous usage of `backdrop-blur` with no apparent visual impact (I only kept it on menu-wrapper, menu-blur, nested-menu, background-blur, and search-wrapper)
- Improves number of draw calls in Firefox with `header = "fixed"` and `layoutBackgroundBlur = false` by **~200 times**, drastically improving scrolling performance
- Improves number of draw calls in Firefox with `header = "basic"` and `layoutBackgroundBlur = true` by ~50%
In my earlier testing, I had simply disabled `.backdrop-blur`, `.backdrop-blur-sm`, and `.backdrop-blur-2xl` on every element except for the search widget, but this is a more proper solution. …
> Remove extraneous backdrop-blurs across partials

- .gitignore
- assets/js/shortcodes/gallery.js
- layouts/partials/vendor.html
- layouts/shortcodes/gallery.html
- package.json
Related to bug issue https://github.com/nunocoracao/blowfish/issues/1125
> 🐛 Shortcodes gallery (non-unique id, multiple loading <script> tag)

- assets/css/compiled/main.css
- assets/css/main.css
This tweaks the CSS to fix https://github.com/nunocoracao/blowfish/issues/990 by adding scroll bars to long KaTeX equations, tables, and inline code sections. The corresponding edits to `assets/css/compiled/main.css` are from the Tailwind compiler.
In the past, such long elements used to break the site layout, render some elements off-screen with no way to view them, and cause menus to be unreachable or impossible to click, especially on mobile devices.
I tested it on an example post similar to the one in the original issue. The scroll bars on these elements will fade in and out as needed, depending on the default behavior of the user's browser.
> Fix wide elements (equations, tables, and inline code) breaking site width and layout

- exampleSite/content/docs/shortcodes/index.md
- layouts/partials/keyword.html
- layouts/shortcodes/keyword.html
- layouts/shortcodes/keywordList.html
This PR implements #1109, adding a keyword component. I'm a Python developer so all of this HTML is new to me, but I've got something that works. Feel free to make any changes or suggest any improvements.
> :sparkles: Keyword shortcode

- layouts/partials/functions/uid.html
- layouts/shortcodes/carousel.html
- layouts/shortcodes/chart.html
- layouts/shortcodes/gallery.html
- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
- layouts/shortcodes/typeit.html
I've experimented with a new way of generating unique IDs. These are used on some shortcodes like `gallery`.
There have been several iterations and all of them have had issues. I submitted a PR time ago (https://github.com/nunocoracao/blowfish/pull/738) that used `.Ordinal` to generate a unique number inside the page, to fix several galleries in the same page having the same ID. It was later discovered that this didn't work properly on nested shortcodes, like for example, inside a timeline (https://github.com/nunocoracao/blowfish/issues/1125#issuecomment-1859979392). The current solution generates an id with a random sequence  of numbers. Even if it would be very rare, it cannot be discarded the possibility of generating the same id twice in the same page. And it could go unnoticed by a …
> New way to generate UIDs.

- layouts/partials/footer.html
Fix https://github.com/nunocoracao/blowfish/issues/943
Support "pre" icon parameter for footer
```
[[footer]]
identifier = "twitter"
pre = "twitter"
name = "Twitter"
url = "https://twitter.com/xxx"
weight = 200
```
> footer menu supports "pre" icon parameter

- i18n/zh-CN.yaml
Translated items retained in English in `zh-CN.yaml`.
> Correct i18n strings

- layouts/shortcodes/gitlab.html
The property `.html_url` is no longer present in `https://gitlab.com/api/v4/projects/<projectID>` endpoint. That renders an empty `href`. Instead, the endpoint returns the property `.web_url`
> fix GitLab shortcode link url

- layouts/partials/header/basic.html
- layouts/partials/header/header-mobile-option-nested.html
- layouts/partials/header/header-mobile-option-simple.html
- layouts/partials/header/header-option-nested.html
- layouts/partials/header/header-option-simple.html
- layouts/partials/translations.html
Hi!
I just fixed some inconsistencies in the header:
- In mobile version, its height would depend on the height of the dark mode switcher. If the user has the switcher disabled, the header would appear very small on mobile.
- Dark mode switcher is smaller on desktop mode than on mobile, and compared to the other icons.
- Dark mode switcher on mobile doesn't have color change on hover, the other buttons have.
- Clickable area in dark mode switcher is much bigger than the other icons (that's why the height of the header in mobile depended on this button).
> Improve consistency in header's layout and size

- layouts/_default/_markup/render-heading.html
While utilizing the theme, it was observed that headings containing non-ASCII characters, such as those in Chinese text, were not positioned when clicked on either the Table of Contents (TOC) or the anchor mark (#) preceding the heading. This issue did not occur with headings in plain English.   
The resolution involved updating the render-heading.html file to implement URL escaping for anchors, enabling accurate positioning for non-ASCII headings.
> 🐛 Anchors Not Functioning Correctly for CJK Headings

- exampleSite/content/docs/configuration/index.md
- exampleSite/content/docs/welcome/index.md
- i18n/ca.yaml
I added the Catalan translation for the default i18n strings. I didn't add the language to the list in the [Configuration page of the documentation](https://blowfish.page/docs/installation/), because it is unclear what flag should be used (if any). For that same reason, I chose to apply the `CA` tag in the YAML file. Any suggestions on how to resolve this would be appreciated.
> :globe_with_meridians: Add Catalan translation

- exampleSite/content/docs/thumbnails/index.md
Current example looks a little bit confusing because the description in the text and the folder structure in the example don't match. The fix makes it more clear to what the user should have and see after making the changes according to the description.
> ✏️ Fix folder structure example on Thumbnails page

- layouts/_default/list.html
FIXED: execute of template failed: template: _default/list.html:23:19: executing "main" at <.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
> 🐛 Fix list.html render issue

- i18n/zh-CN.yaml
- i18n/zh-TW.yaml
change `ZH-CN` in` i18n/zh-CN.yaml` to `简体中文`.
https://github.com/nunocoracao/blowfish/issues/1358
Maybe "language" in i18n/[language-code].yaml is only display name, so translate zh-CN to 简体中文 in i18n/zh-CN.yaml is reasonable.
> 🎏 update language in i18n/[language-code].yaml

- layouts/partials/toc.html
If a header text contains CJK characters, the anchor id of it will be encoded.
For example, the id of [`Icon 图标`](https://blowfish.page/zh-cn/docs/partials/#icon-%E5%9B%BE%E6%A0%87) is `icon-%E5%9B%BE%E6%A0%87`. 
So the set active actions for TOC with `('a[href="#' + id + '"]').addClass('active')` will be impossible to set to the right TOC element, since the id equals `icon-%E5%9B%BE%E6%A0%87` and the href in TOC is `#icon-图标`.
A simple conversion with decodeURIComponent() will fix this well.
> 🐛 Fix TOC scroll indicator with CJK characters

- exampleSite/content/docs/shortcodes/index.md
- layouts/_default/_markup/render-image.html
- layouts/_default/_markup/render-link.html
- layouts/shortcodes/figure.html
Due to the way the old shortcode was written, weird cosmetic errors like the one below were cropping up:
The input Markdown was:
```md
2. The ANTLR generated files generate huge diffs when changes are made to the grammar files. ([Here is an example.](https://github.com/sympy/sympy/pull/23535/files))
```
I changed the shortcode to not add that spurious space.
 
When I was investigating the HTML output for the image shortcodes, I noticed two things:
1. Usage of the image shortcodes introduced a lot of newlines into the output HTML. While it's not a big deal in production, it made debugging a little annoying. I removed all the whitespace from the image shortcodes.
2. Including a local SVG in the image shortcodes, when `disableImageOptimization` is `false`, would cause the Hugo build to fail …
> 🎨 Improvements to image handling and link handling

- data/sharing.json
- exampleSite/config/_default/params.toml
- i18n/en.yaml
- package.json
Added:
- Bluesky definition in data/sharing.json
- Bluesky to exampleSite params.toml
- Alt text to i18n/en.yaml
Enables the addition of "bluesky" to the default article sharing links using the Action Intent link defined here: https://docs.bsky.app/docs/advanced-guides/intent-links
> :sparkles: Add data definition for sharing on Bluesky

- exampleSite/content/docs/shortcodes/index.it.md
- exampleSite/content/docs/shortcodes/index.ja.md
- exampleSite/content/docs/shortcodes/index.md
- exampleSite/content/docs/shortcodes/index.zh-cn.md
- layouts/shortcodes/codeimporter.html
- I'm writing a blog that needs to import code from GitHub, but only a specific range of code.
- The current `codeimporter` shortcodes don't provide this feature.
- If `startLine` and `endLine` are not provided, the whole code will be imported .
- Updated the docs and provided examples as well (have run `npm run example`, works nicely).
Working example on my blog:
```md
{{< codeimporter url="https://raw.githubusercontent.com/redis/redis/811c5d7aeb0b76494d78efe61e418f574c310ec0/src/rdb.c" type="c" startLine="3907" endLine="3942">}}
```
Big thanks for sharing this theme 💯
I'm enjoying the i18n support and wonderful UX. I will promote it to my friends 🙌
> ✨ Add startLine, endLine Support for `codeimporter`

- layouts/_default/single.html
Closes #1627 
This PR corrects the URLs for the author pages. 
Without this PR, the URL contains doubled slash and has no trailing slash.
With this PR, the generated URL does not contain any doubled slash, and has correct trailing slash.
> fix: correct links for the author pages

- assets/css/compiled/main.css
- assets/css/main.css
- layouts/partials/header/basic.html
This is my proposal to use an SVG as `.Site.Params.Logo`. 
Additions, hints and corrections are welcome!
> ✨ add SVG support for logos

- assets/js/search.js
Do not prevent default for "Enter" if search is not visible. Old logic would prevent comment system adding new line using "Enter"
Related to this issue https://github.com/nunocoracao/blowfish/issues/1682
> 🐛 Do not prevent default for Enter

- exampleSite/content/docs/shortcodes/index.it.md
- exampleSite/content/docs/shortcodes/index.ja.md
- layouts/shortcodes/button.html
`rel` attribute is added to button shortcode.
> ✨ Add rel attribute to button shortcode

- layouts/partials/header/header-mobile-option-nested.html
Allow access to content on mobile, when there are sub-menus.
Fixes #1230
> Fix mobile menus to allow access to menu content

- exampleSite/content/docs/getting-started/index.it.md
- exampleSite/content/docs/getting-started/index.ja.md
- exampleSite/content/docs/getting-started/index.md
- exampleSite/content/docs/getting-started/index.zh-cn.md
See past PRs #1681 & #1708.
I've left the occurrences in [`exampleSite/content/guides/202310-blowfish-tutorial`](https://github.com/nunocoracao/blowfish/tree/c2db79ee4b1208fcaa3f2428f1dd39d15bdb1731/exampleSite/content/guides/202310-blowfish-tutorial) alone, as I assume that guide is frozen in time.
> 📝 change [author] to [params.author] also in "Basic configuration" docs

- layouts/partials/article-meta/basic.html
Currently, clicking any terms within a list will **not** redirect to the intended location, due to navigation event bubbling up.
We can easily verify this by checking the network log in chrome.
Navigate to https://blowfish.page/samples/ and click the `authors` term. We will be redirected to the `a` tag `href` instead of the `authors` term page.
This can be easily fixed, returning `false` from the `onclick` handler, thus canceling the parent `a` tag navigation.
> 🐛 Update basic.html so navigation doesn't bubble up.

- assets/css/compiled/main.css
- layouts/partials/header/basic.html
- layouts/partials/translations.html
Relevant issue: #1871 
In RTL languages, the layout of the top nav bar is slightly broken:
In desktop mode, there's no gap between **EN** and the languages logo, and there's no gap between **Shortcodes** and **Docs** tabs
In mobile mode, there's no gap between **EN** and the languages logo.
The issue is mainly caused by two things:
- Usage of `mr-X` or `ml-X` in some places, which places the margin in the wrong direction when switched to RTL layout. This is solved by making use of `rtl:` and `ltr:` specifiers. So `mr-1` is changed to `ltr:mr-1 rtl:ml-1`
- Usage of `space-x-X` in some places, which doesn't work well with RTL layouts. This is solved by replacing `space-x-X` with `gap-x-X`.
Desktop mode.
Mobile mode.
> 🐛 RTL top nav bar layout fix.

- exampleSite/content/samples/icons/index.md
There was a minor grammar error in the SVG icons docs page, which I fixed.
> Update SVG icon docs

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/timelineItem.html
The `text` option was undocumented and also not used anywhere in the shortcode.
> Remove unused option in `timeline` shortcode

- layouts/shortcodes/gist.html
Since the gist shortcode was deprecated in v0.143.0 and will be removed in a future release of Hugo, I followed the instructions provided by [Hugo](https://gohugo.io/shortcodes/gist/).
> ✨ Create gist.html

- assets/js/mermaid.js
- layouts/shortcodes/mermaid.html
Add a pre tag to the Mermaid class to preserve indentation and ensure data retrieval on DOMContentLoaded. This should close #2069.
> 🐛 fix: Preserve Mermaid indentation disrupted by Hugo minify (#2069)

- layouts/partials/head.html
This pull request avoids adding `mailto:x@y.z` links inside the `head` tag. As far as I know there is no real use for it anyway, but not adding it would enable users to use Cloudflare's [Email Address Obfuscation](https://developers.cloudflare.com/waf/tools/scrape-shield/email-address-obfuscation/) correctly as Cloudflare does _not_ remove these inside of the `head` tag.
> ✨ don't add `mailto:` links to `<head>`

- layouts/shortcodes/gallery.html
This PR fixes the gallery path error (#2042) by using `resource.RelPermalink`. Since the document uses `<img>` tags in the gallery shortcode, a regex is needed to properly resolve the `<img>` tag.
In the following example, all images work as expected on default language pages. However, on non-default language pages, images will not be displayed if `<img>` tags are not used in the image shortcode, which is the same behavior as before this PR.
```md
{{< gallery >}}
<picture class='grid-w50 md:grid-w33 xl:grid-w25'>
<source srcset='gallery/01.jpg' type='image/jpeg'>
</picture>
<embed src='gallery/02.jpg' type='image/jpeg' class='grid-w50 md:grid-w33 xl:grid-w25' />
<object data='gallery/03.jpg' type='image/jpeg' class='grid-w50 md:grid-w33 xl:grid-w25'></object>
{{< /gallery >}}
```
> 🐛 fix: incorrect path for gallery (#2042)

- assets/css/compiled/main.css
- assets/css/main.css
Fix the issue where long text overflows in the copy button.
Before:
After:
> 🐛 Fix: truncate long text in copy-button

- assets/js/search.js
> 🐛 Fix: disable the search keyboard shortcut in a form (#2041)

- assets/css/compiled/main.css
- assets/css/main.css
- layouts/partials/toc.html
This PR fixes two ToC issue.
| Before Fix | After Fix |
|------------|-----------|
| ![Before](https://github.com/user-attachments/assets/6ebc067f-3d7e-40a7-85eb-7394805acb9f) | ![After](https://github.com/user-attachments/assets/3dd6eac3-bad1-4f54-bb6e-33d7525c567c) |
<br><br>
Use CSS to control ToC height instead of JavaScript to prevent flicker, this also enable scrollbar under no-JS environment.
| Before Fix | After Fix |
|------------|-----------|
| ![a_2x](https://github.com/user-attachments/assets/a89be08b-0c25-4d6a-be46-d59341ac6403) | ![b_2x](https://github.com/user-attachments/assets/cc84b5fc-9299-46b2-a29b-cd05771cf107) |
> ✨ Improved Table of Contents Display

- exampleSite/config/_default/hugo.toml
- exampleSite/config/development/hugo.toml
- package.json
This PR introduces two new development commands—`example:site_core` and `example:site_core:en_only` to significantly reduce development CPU usage without disrupting existing workflows. Since we typically focus on `shortcode` and `samples` pages during development, rendering the entire site is unnecessary.
|                  | `npm run example` (original) | `npm run example:site_core` | `npm run example:site_core:en_only` |
| ---------------- | ----------------- | --------------------------- | ----------------------------------- |
| Pages            | 1400              | 132                         | 34                                  |
| Non-page files   | 800               | 224                         | 56                                  |
| Images processed | 289               | 12 …
> 🧑‍💻 chore: add options for faster development

- layouts/_default/_markup/render-image.html
Previously, the image always displayed the largest available (but still compressed) version, without selecting an appropriate size based on the device. Additionally, it never showed the original image, which negatively affects users who use Blowfish as an image gallery.
Changes made:
1. Remove the `x` descriptor
> It is incorrect to mix width descriptors and pixel density descriptors in the same `srcset` attribute.  
> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img#attr-srcset  
2. Set `data-zoom-src` to point to the original, uncompressed image
3. Remove sizes 1024 and 1320 due to minimal difference; replace with 1280
4. With change `3`, conversion speed is about twice as fast as 1024 and 1320 are very close. Also, I tested and found that the gap only affects a …
> 🐛 fix: Correct the attributes of the `<img>` tag

- config/_default/hugo.toml
In Hugo v0.132.0, the Goldmark passthrough extension was introduced to preserve raw Markdown text within designated delimiters, ensuring that MathJax or KaTeX can render formulas correctly. With this configuration in place, you no longer need to manually escape characters inside math expressions (for example, \\ → \\\\ or x_y → x\_y).
According the official document of Hugo:  
- [mathematics/#step-1](https://gohugo.io/content-management/mathematics/#step-1)
- [Passthrough render hooks](https://gohugo.io/render-hooks/passthrough/)
> Enable Goldmark passthrough extension for math rendering

- layouts/partials/head.html
Fix #1781: Use extend-head-uncached.html for backward compatibility.
> ✨ Feat: support extend-head access .Page (#1781)

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/github.html
Option to show thumbnails (opengraph previews) for GitHub cards:
```mustache
{{< github repo="nunocoracao/blowfish" showThumbnail=true >}}
```
> ✨ feat(shortcodes): Display thumbnails for GitHub repos

- layouts/partials/toc.html
This PR fixes the issue where `smartTOCHideUnfocusedChildren` did not collapse higher-level TOC items that were outside the current viewport. Previously, only the immediate children were collapsed.
In addition, this PR improves performance and maintainability by:
1. Eliminating jQuery dependency in TOC scroll handling logic.
2. Using native DOM APIs with pre-cached anchor and link references to avoid repeated DOM queries on scroll.
3. Leveraging passive event listeners for better scroll performance.
Before
https://github.com/user-attachments/assets/c582478b-e673-4505-8965-0b24b8b3eb1e
After
https://github.com/user-attachments/assets/0ca3294f-d825-410f-9d5d-3df37a260e15
> 🐛 Fix: smartTOCHideUnfocusedChildren not collapsed

- layouts/partials/toc.html
Based on #2202, fix TOC active state loss caused by dynamic content adding extra anchors not in TOC (e.g. mdimporter).
Limit active anchor detection to only those referenced in the TOC.
> 🐛 Fix TOC Active State Loss with Dynamic Content

- assets/js/background-blur.js
- assets/js/fetch-repo.js
- assets/js/page.js
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/_default/term.html
- layouts/_default/terms.html
- layouts/partials/header/fixed-fill-blur.html
- layouts/partials/header/fixed-gradient.html
- layouts/partials/header/fixed.html
- layouts/partials/hero/background.html
- layouts/partials/hero/thumbAndBackground.html
- layouts/partials/home/background.html
- layouts/shortcodes/codeberg.html
- layouts/shortcodes/forgejo.html
- layouts/shortcodes/gitea.html
- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
- Move variables oid, oid_likes out of line
- Move background-blur out of line
- Move fetch-repo code out of line
[See this](https://github.com/nunocoracao/blowfish/discussions/2198) for an explaination as to why. It's just a start, but this alone reduces inline scripts by a lot and should actually improve readability and maintainability as far as I know.
I just chose scripts that are very similar for now since having those as inline scripts is in my opinion a real burden to maintain.
I have tested that this is working locally (See the video for details) (Superseded by: https://github.com/nunocoracao/blowfish/pull/2209#issuecomment-2980478187):
https://github.com/user-attachments/assets/d5ee6a80-cf51-451c-a11a-b8af575ef6f7
On the preview page the forgejo card is as bugged as on …
> :recycle: refactor: Move similar javascript inline code out of line

- assets/css/compiled/main.css
- assets/css/main.css
- layouts/_default/_markup/render-heading.html
- layouts/_default/list.html
- layouts/_default/term.html
- layouts/partials/article-meta/basic.html
- layouts/partials/badge.html
- layouts/partials/header/basic.html
- layouts/partials/header/fixed-fill-blur.html
- layouts/partials/header/fixed-fill.html
- layouts/partials/header/fixed-gradient.html
- layouts/partials/header/fixed.html
- layouts/partials/hero/big.html
- layouts/partials/home/background.html
- layouts/partials/home/card.html
- layouts/partials/home/hero.html
- layouts/partials/meta/likes_button.html
- layouts/partials/recent-articles/cardview-fullwidth.html
- layouts/partials/search.html
- layouts/partials/series/series-closed.html
- layouts/partials/series/series.html
- layouts/shortcodes/codeberg.html
- layouts/shortcodes/forgejo.html
- layouts/shortcodes/gitea.html
- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
- package-lock.json
- Move out of line by using already defined css classes
- Move paddings out of line
- Move margins out of line
- Move z-indexes out of line
- Move center-relative-left out of line
I haven't tested everything in detail, but after a few minutes of navigating I haven't noticed any differences.
I'm not sure if I'm supposed to build `main.css` manually or if that is done while deploying. If it isn't please let me know and I will rebuild it. (Solved: https://github.com/nunocoracao/blowfish/pull/2211#issuecomment-2945422610)
The reason for this is also related to [this discussion](https://github.com/nunocoracao/blowfish/discussions/2198). It however should also improve readability and especially maintainability. Also everything being in `main.css` as far as I know could even improve performance …
> :recycle: refactor: Move most inline styles out of line

- layouts/partials/hugo-embedded/shortcodes/figure-default.html
- layouts/shortcodes/figure.html
I updated the blowfish submodule in my Hugo project and ran into the error `partial "shortcodes/figure.html" not found`. It has already been discussed in #2052, #2053, then reported again in #2093. However, [this fix](https://github.com/nunocoracao/blowfish/pull/2055/files#diff-dd648b847f1ddc24890196195d38087229de05e7b6a08bbf2de0da28c4765244R3) from #2053 doesn't solve the problem, because, from what I gather, `partial` doesn't have access to embedded shortcodes anymore.
This PR has the embedded `figure` shortcode renamed and copied to partials. This seems to be the way to fix such issues as of now.
**Update**:
I see that another way to fix this is to revert the fix linked above for the figure shortcode and keep `{{ template "_internal/shortcodes/figure.html" . }}`. Even though, it is …
> 🐛 fix: add default figure shortcode as partial

- exampleSite/content/docs/advanced-customisation/index.it.md
- exampleSite/content/docs/advanced-customisation/index.ja.md
- exampleSite/content/docs/advanced-customisation/index.md
- exampleSite/content/docs/advanced-customisation/index.zh-cn.md
With the upgrade to Tailwind v4 in v2.83.0, the Tailwind CLI moved from being in the `tailwind` package to a separate `@tailwindcss/cli` package. This PR updates the documentation for setting up the Tailwind compiler to use this new CLI path.
> 📝 Docs: Update Tailwind CLI docs for Tailwind v4

- layouts/partials/vendor.html
This renames $youtubeLiteJS $youtubeLiteLib to match the naming of other files in assets/lib and moves the initialization of $youtubeLiteLib to the bottom, above the script element
This also adds 3 missing fingerprints, one to $packeryLib, one to $twelementsLib and one to $youtubeLiteCSS
Previously, this was part of https://github.com/nunocoracao/blowfish/pull/2231 and https://github.com/nunocoracao/blowfish/pull/2218, but after some thinking, I just split up the PR.
> :art: Structure: Restructure vendor.html and add missing hugo fingerprints

- assets/js/button-likes.js
- assets/js/katex-render.js
- layouts/partials/head.html
- layouts/partials/meta/likes_button.html
- layouts/partials/vendor.html
If MDN explicitly warns user not to use them, we probably shouldn't.
MDN also states: "Note that inline event handlers are blocked as well[...]You should replace them with addEventListener calls[...]" regarding CSP.
Previously, this was part of https://github.com/nunocoracao/blowfish/pull/2231 and https://github.com/nunocoracao/blowfish/pull/2218, but after some thinking, I just split up the PR.
> :recycle: Refactor: Move 2 inline event handlers out of line

- .prettierignore
- layouts/partials/article-link/_external-link.html
- layouts/partials/article-link/card-related.html
- layouts/partials/article-link/card.html
- layouts/partials/article-link/simple.html
This PR abstracts anchor attributes to enable formatting of article links.
To achieve this, an additional partial file was introduced. Given that only three files require formatting, the cost of adding a new file should be carefully evaluated. While using an [inline partial](https://gohugo.io/functions/go-template/define/) can avoid creating a new file, embedding an inline partial inside the article-link file may cause confusion for users.
This PR performs the same task as #2179.
> ♻️ Refactor: make article-link formattable

- config/_default/module.toml
Removes the content of the module.toml file to resolve the conflict with config.toml.
> 🐛 Fix: minimum version warning not working

- layouts/_default/_markup/render-link.html
> 🐛 Fix: render-link.html adding space after each link

- layouts/partials/article-link/card-related.html
- layouts/partials/article-link/card.html
- layouts/partials/article-link/simple.html
- layouts/partials/article-meta/basic.html
- This removes an inline event handler
- This also adds an aria-label
Using javascript instead of just using `<a>` tag is bad practice regarding accessibility and automated processing of web pages. Even the browser doesn't show a hint if hovering badges when using the old implementation. This in my opinion is a good way to replace inline event handlers in that code.
Previously, this was part of https://github.com/nunocoracao/blowfish/pull/2231 and https://github.com/nunocoracao/blowfish/pull/2218, but after some thinking, I just split up the PR.
> :warning: This currently isn't compatible with https://github.com/nunocoracao/blowfish/pull/2249 and https://github.com/nunocoracao/blowfish/pull/2268. Please notify me to make the necessary changes.
> :children_crossing: UX: Use anchor tags in article-meta/basic.html

- assets/css/compiled/main.css
- layouts/_default/_markup/render-heading.html
Prevent the anchor element from being selected, so that the # symbol is not copied.
> 💄 Style: prevent anchor from being selected

- layouts/_default/_markup/render-image.html
Support displaying Base64-formatted images in Markdown files. 
It is worth noting that there seem to be [other issues](https://discourse.gohugo.io/t/markdown-insert-base64-image-error-file-name-too-long/55307/4?u=onqiaujliu) with this file.
#2221
> :sparkles: Feat: Support base64 image format

- layouts/partials/article-link/_shortcode.html
Without this, the `href` in the article shortcode will be to the current page not the specified `link=`.
Also see: https://github.com/nunocoracao/blowfish/pull/2297#issuecomment-3085165961
@nunocoracao please merge this before publishing the next release. Thanks in advance!
:warning: There are probably merge conflicts with https://github.com/nunocoracao/blowfish/pull/2351 . To fix without me just merge https://github.com/nunocoracao/blowfish/pull/2351 first and then merge only the change to `$target` from this.
> :ambulance: Hotfix: Fix incorrect href in article shortcode

- layouts/partials/icon.html
- layouts/shortcodes/icon.html
Closes #2371, see [this](https://discourse.gohugo.io/t/tableofcontents-doesnt-render-headings-correctly-that-contains-shortcode/55399/5). Also aligns the error message with other repo cards.
> 🐛 Fix(icon): trim white space and line break

- layouts/shortcodes/carousel.html
The original interval didn't work because `duration-[{{ $interval }}ms]` can't be inferred by Tailwind and not viable for downstream users.
Carousel in v2.88.1:
https://github.com/user-attachments/assets/68ffc5f9-53f7-4722-ab79-eb8ffbcc71c4
Carousel in this PR:
https://github.com/user-attachments/assets/8b333eb9-0ba7-4e76-8add-b8d795ca320a
> 🐛 Fix(carousel): interval not working

- layouts/shortcodes/carousel.html
As the title says, the transition time isn't controlled by the interval.
Since I'm not sure if this is the intended behavior, this is submitted as a separate PR. It also slows down the image transition when clicking the slide button.
Carousel in #2373:
https://github.com/user-attachments/assets/17940792-4ab8-4c60-8447-6812a86bc8a7
Carousel in this PR:
https://github.com/user-attachments/assets/c47548e9-b673-4090-8422-1f3568b1c890
> 🐛 Fix(carousel): transition time not controlled by interval

- i18n/en.yaml
Adding missing title for the "Share to Mastodon" link in the English language. Currently, hover over the Mastodon sharing link at the bottom of single pages doesn't do anything. With the proposed changes, a tooltip with `Share via Mastodon` appears upon hover, which is consistent with the behavior observed with the other share links.
> Fix(link-title): Add missing English title for the share to Mastodon link.

- exampleSite/layouts/partials/recent-articles-demo.html
- layouts/partials/header/basic.html
- layouts/partials/header/header-mobile-option-nested.html
- layouts/partials/header/header-mobile-option-simple.html
- layouts/partials/header/header-option-nested.html
- layouts/partials/header/header-option-simple.html
- layouts/partials/home/background.html
- layouts/partials/home/card.html
- layouts/partials/home/hero.html
- layouts/partials/recent-articles/main.html
- layouts/partials/translations.html
- layouts/shortcodes/carousel.html
While answering #2396, I discovered that enabling Tailwind's default colors breaks the current layout. This should not happen. I suspect it is because some classes use Tailwind's default color palette but have no effect since they are not being compiled. Therefore, the layout breaks when enabling the default color palette.
Here is how I located the problematic classes:
1. Enabling the default colors
2. Compiling the CSS
3. Finding them in the diff of the compiled output
After removing the unused classes, the layout stays visually stable, even with the default color palette enabled.
> 🔧 Chore: prune unused Tailwind classes
