nunocoracao/blowfish

- layouts/_default/single.html
- layouts/partials/meta/views.html
> Update .Path to .File.Path to fix deprecation warnings.

- i18n/pl.yaml
Hey!
Recently I found this theme and I saw that there is a polish translation missing. I wrote this, maybe it will be useful for someone.
> Add pl.yaml Polish Translation

- layouts/partials/head.html
This doesn't look like it is used?
> Remove Inter font CSS

- exampleSite/content/docs/configuration/index.md
Slight change from Hrvatski to Croatian as it is generally more accepted term.
> Slight fix for the name.

- exampleSite/content/users.md
> update user list

- i18n/ja.yaml
there are a few strings I saw that I thought could be expressed a little more naturally.
> improved Japanese translation

- package-lock.json
- package.json
Reverts nunocoracao/blowfish#223
> Revert "📌 Bump @tailwindcss/typography from 0.5.7 to 0.5.8"

- exampleSite/content/users/_index.md
I wanted to add my personal site to the list as well.
> :busts_in_silhouette: ADD: User to user list

- exampleSite/content/users/_index.md
Requesting an add to the users index page :)
> :busts_in_silhouette: Add blog to users/_index.md

- assets/css/compiled/main.css
- exampleSite/content/users/index.md
- layouts/_default/baseof.html
- layouts/partials/footer.html
Moved the scroll to top button to stop it from overlapping with footer text.
fixes #294
> 💄 add margin-bottom to 'the-top' element

- theme.toml
> :pencil2: Fixing small typo in theme.toml

- exampleSite/content/docs/advanced-customisation/index.md
- exampleSite/content/docs/partials/index.md
Updated docs in reference to #336
> Update docs in regards to image optimization

- i18n/pt-BR.yaml
Signed-off-by: igorr0driguez <42983358+igorr0driguez@users.noreply.github.com>
pt-BR translation update.
> :globe_with_meridians: pt-BR translation update

- exampleSite/content/users/index.md
> 👤Added another user, great theme.

- exampleSite/content/docs/shortcodes/index.md
> :memo: update github shortcode

- exampleSite/content/docs/homepage-layout/index.md
> 📚 spelling error.

- i18n/fr.yaml
Here is the French translation for the serie part.
> 🌐 Fix french translation

- exampleSite/content/users/index.md
Added my blog to the example users: blog.muffn.io
> 👤 update index.md w/ blog.muffn.io

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/alert.html
> ✨ Custom colors for alert shortcode

- exampleSite/content/users/index.md
Thanks Nuno, for creating and maintaining Blowfish. I had a blast making my personal site with it!  🥳
> 👤add alanctanner.com to users/index.md

- layouts/partials/header/basic.html
- public/404.html
- public/authors/index.html
- public/categories/index.html
- public/index.html
- public/series/index.html
- public/tags/index.html
Hi,
I am just adding an aria label to the search and dark mode switch buttons to improve accessibility ♿️
More information about accessibility is [available here](https://dequeuniversity.com/rules/axe/4.4/button-name)
Enjoy 🪂
> ♿️ Add aria-label on buttons

- exampleSite/content/users/index.md
also removed some capital letters for consistency's sake
> add rdgo.dev to the list

- exampleSite/content/docs/configuration/index.md
- i18n/vi.yaml
Hi,
I'm Viet and I would like to add Viet lang in this theme.
Please approve.
Thanks.
> add Vietnamese language

- layouts/partials/home/background.html
- layouts/partials/home/hero.html
- layouts/partials/translations.html
Increase spacing for easier touch
Add link to language switcher
> ♿️ Minor changes

- exampleSite/content/docs/shortcodes/index.md
Fix copy-paste error in responsive gallery code sample
> Fix copy-paste error in responsive gallery code sample

- exampleSite/content/users/index.md
add a personal site https://ripplesding.github.io
> 👤 Update index.md

- layouts/shortcodes/carousel.html
> Accessibility: add alt tag to carousel

- layouts/_default/_markup/render-heading.html
> fix: Remove heading anchor content

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/gitlab.html
#639 PR with prototype implementation of the proposed shortcode.
It is a simple adaptation of the current github shortcode.
> ✨ Add gitlab shortcode

- assets/css/compiled/main.css
- layouts/shortcodes/article.html
- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
- tailwind.config.js
https://github.com/nunocoracao/blowfish/issues/663
> fixed 🎨 List hover styling too bright

- i18n/bg.yaml
Not sure if [this page](https://blowfish.page/docs/welcome/#multilingual-support) should also be updated to reflect the actual number of translations (probably for a separate PR, anyway).
Also, thank you for this great theme! ⭐
> :globe_with_meridians: Add Bulgarian translation

- exampleSite/content/users/index.md
Signed-off-by: Clément Sauvage [cl.sauvage@yahoo.com](mailto:cl.sauvage@yahoo.com)
Add [clemsau.com](https://clemsau.com) website.
> 👤 Add clemsau.com personal site

- exampleSite/content/docs/configuration/index.md
- i18n/bg.yaml
- Update language list in documentation.
- Replace language code with emoji.
- Translate newly-added 'related articles' string.
> 🌐Update Bulgarian translation

- assets/js/process.js
Reverts nunocoracao/blowfish#709
> Revert "🐛 Fixed error getting views and likes on a Windows built site."

- assets/js/process.js
Reverts nunocoracao/blowfish#711
> Revert "Revert "🐛 Fixed error getting views and likes on a Windows built site.""

- assets/css/compiled/main.css
- assets/js/appearance.js
- layouts/partials/footer.html
- layouts/partials/scroll-to-top.html
fixed https://github.com/nunocoracao/blowfish/issues/696
> 🐛 Move to top gap between content and icon

- assets/css/compiled/main.css
- tailwind.config.js
fixed https://github.com/nunocoracao/blowfish/issues/703
> 🐛 Links become white on hover in light theme

- layouts/partials/head.html
…for site's meta description
fixes https://github.com/nunocoracao/blowfish/issues/690
> ✨ frontmatter uses both summary and description

- layouts/partials/header/header-option-nested.html
I hope this is okay.
I am explicitly checking if there even is a url, and if so, include it.
> ✨ Fix missing URL for Top-level menu entry in nested menu

- exampleSite/content/users/index.md
Add [weaxsey.org](https://weaxsey.org/) website, please accept , thx.
repository: https://github.com/Weaxs/weaxsey.org.
Build based on docker compose.
> 👤 Added weaxsey.org

- exampleSite/content/users/index.md
This PR add my personal site to this [https://blowfish.page/users/](https://blowfish.page/users/) page.
> add (users): nikarashihatsu.github.io

- exampleSite/content/users/index.md
Add blog.enmanuelmoreira.com to blog user's list
> Add blog.enmanuelmoreira.com

- config.toml
fixes https://github.com/nunocoracao/blowfish/issues/755
> ⬆️ increase max supported version of Hugo

- layouts/partials/analytics.html
This is my attempt to fix #766.
I spent just enough time on this to fix the issue for me. I haven't done any testing beyond validating that Fathom works again.
Thank you for the great work on that awesome theme!
> 766 - fix analytics partial to make fathom analytics configurable

- exampleSite/config/_default/params.toml
- layouts/partials/analytics.html
- layouts/partials/analytics/fathom.html
- layouts/partials/analytics/ga.html
- layouts/partials/analytics/main.html
- layouts/partials/head.html
fixed https://github.com/nunocoracao/blowfish/issues/766
> 🐛 Fix and refactor analytics

- exampleSite/content/docs/thumbnails/index.md
> ✍🏼 Typos + grammar tweaks

- exampleSite/content/users/index.md
Added personal comics site made in Blowfish to users list.
> 👤 Added personal comics site made in Blowfish to users list.

- exampleSite/content/users/index.md
- layouts/_default/single.html
- layouts/partials/author.html
fixes https://github.com/nunocoracao/blowfish/issues/771
> 🎨 author on top of articles

- exampleSite/content/users/index.md
I added my personal site to the example site.
> 👤 Add my personal site

- i18n/es.yaml
Added missing texts and some corrections:
- More consistent capitalization.
- Avoid using the word "Link" which is an anglicism.
> 🎏 Update to the Spanish translation

- assets/css/compiled/main.css
- layouts/partials/header/basic.html
https://github.com/nunocoracao/blowfish/issues/775
> 🐛 Fix menu wrapper for Safari

- config.toml
https://github.com/nunocoracao/blowfish/issues/807
> ⚙️ Add support for Hugo v0.115.3

- assets/css/compiled/main.css
- layouts/_default/single.html
Fixes https://github.com/nunocoracao/blowfish/issues/820
> 🎨 TOC moves out of the screen because of related articles

- exampleSite/content/users/users.json
> Add my personal site to users.json

- layouts/_default/rss.xml
fix build error in rss.xml
closes #825
> 🐛 fix(build): LanguageCode in rss.xml

- layouts/partials/home/background.html
> 🎨 Adjust margin-top of author links for a more balanced look

- exampleSite/content/users/users.json
> 👤 Update users.json

- assets/css/compiled/main.css
- assets/css/main.css
- layouts/_default/single.html
fixes https://github.com/nunocoracao/blowfish/issues/856
> 🐛 Mobile bug in articles

- exampleSite/content/users/users.json
> Add bbagwang.com in users.json

- layouts/shortcodes/carousel.html
- layouts/shortcodes/chart.html
- layouts/shortcodes/gallery.html
- layouts/shortcodes/typeit.html
Fixes https://github.com/nunocoracao/blowfish/issues/886
> 🐛 updated logic for unique ids in shortcodes

- layouts/partials/home/hero.html
Sorry for accidentally open this PR earlier.
This is the same fix for the closed issue #837 but on the hero layout!
> 🎨 Adjust margin-top for a more balanced look

- exampleSite/content/docs/getting-started/index.md
Documenting default name, and clarifying sentence.
Follow up to https://github.com/nunocoracao/blowfish/pull/893.
> 📖 Clarifying sub-menu docs

- config.toml
fixes https://github.com/nunocoracao/blowfish/issues/945
> ⚙️ Added support for Hugo v0.118.2

- exampleSite/content/users/users.json
Fixes https://github.com/nunocoracao/blowfish/pull/937
> 👤 Add user moccolfc

- config.toml
Fixes https://github.com/nunocoracao/blowfish/issues/968
> ⚙️ added support for Hugo v0.119.0

- exampleSite/content/users/users.json
> 👤 Add my tech blog url to users.json

- exampleSite/content/users/users.json
> add website

- exampleSite/content/users/users.json
Added myself to `exampleSite/content/users/users.json` as I use a blowfish site 🙂
> Add user site - Joush007

- layouts/shortcodes/carousel.html
- package-lock.json
Fix https://github.com/nunocoracao/blowfish/issues/1030
> 🐛 Fixed carousel transition interval not working

- layouts/shortcodes/github.html
- layouts/shortcodes/gitlab.html
Fix https://github.com/nunocoracao/blowfish/issues/1023
> ✨ Make GitHub and GitLab shortcodes update dynamically

- config.toml
https://github.com/nunocoracao/blowfish/issues/1065
> updated support for version 0.120.4 of Hugo

- exampleSite/content/docs/partials/index.md
According to #901 , update custom analytics providers doc.
> 📖 Fix custom analytics doc

- layouts/_default/_markup/render-heading.html
Fixes https://github.com/nunocoracao/blowfish/issues/959
> 🐛 Heading first-child styling not working

- assets/css/compiled/main.css
- assets/css/main.css
- exampleSite/content/_index.md
Fixes https://github.com/nunocoracao/blowfish/issues/957
> Don't center-align code within blocks

- layouts/partials/header/basic.html
Fixes https://github.com/nunocoracao/blowfish/issues/949
> Empty hamburger visible

- layouts/partials/home/background.html
- layouts/partials/home/hero.html
fixes https://github.com/nunocoracao/blowfish/issues/1053
> reduce icon spacing

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/list.html
Fixes https://github.com/nunocoracao/blowfish/issues/1074
> ✨ Card View in List Shortcode

- assets/css/compiled/main.css
- assets/js/process.js
- config.toml
- layouts/partials/meta/likes.html
- layouts/partials/meta/views.html
Fixes https://github.com/nunocoracao/blowfish/issues/1094
> 🎨 Implement loaders for fetched information (views and likes)

- assets/js/search.js
Fixes https://github.com/nunocoracao/blowfish/issues/1104
> 💖 Handle Enter key in search

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/mdimporter.html
Fixes https://github.com/nunocoracao/blowfish/issues/1115
> ✨ External Markdown Importer Shortcode

- exampleSite/content/users/users.json
Hi, I am using your theme and would be happy to be on the list of users.
Have a lovely day 🌞.
Mark
> add the-maze.net to users list

- exampleSite/content/users/users.json
https://datatodroids.tech/ is my personal site and blog created with blowfish
> 👤 add datatodroids.tech example site

- exampleSite/content/users/users.json
Added my own Hugo/Blowfish powered website (www.dxpetti.com) to the users.json list
> Added myself to users.json

- exampleSite/content/users/users.json
> add my blog to users.json

- config.toml
closes https://github.com/nunocoracao/blowfish/issues/1194
> updated hugo version

- assets/js/shortcodes/gallery.js
close https://github.com/nunocoracao/blowfish/issues/1198
> 🐛 fix gallery js code

- exampleSite/content/users/users.json
I'm so sorry for submitting PR so often 😅
Yesterday I purchased a domain [karlukle.site](https://karlukle.site) and deployed GitHub Pages on the new domain, so the URL changed.
Also, the avatar on my blog homepage was changed to a new one, so hope you can take a new snapshot of it.
> Update my site link

- i18n/es.yaml
Hi!
I just added some missing texts to have the language up to date.
> Updated Spanish translation

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/carousel.html
close https://github.com/nunocoracao/blowfish/issues/736
> ✨ carousel support for URLs

- assets/js/code.js
- exampleSite/content/_index.md
Close https://github.com/nunocoracao/blowfish/issues/1236
> 🐛 Code copy doesn't work with gist

- layouts/shortcodes/carousel.html
Fixes https://github.com/nunocoracao/blowfish/issues/1245
> 🐛 Carousel doesn't work for local images

- i18n/zh-TW.yaml
Translated items retained in English in zh-TW.yaml.
> 🌐 Correct I18n Strings

- assets/css/compiled/main.css
- layouts/partials/home/hero.html
Close https://github.com/nunocoracao/blowfish/issues/1288
> 🐛 fixed hero home layout

- assets/css/compiled/main.css
- tailwind.config.js
> 🐛 Tailwind Colors are not updating with colorScheme

- layouts/partials/author.html
- layouts/partials/translations.html
- [Add remote image support to author image](https://github.com/nunocoracao/blowfish/commit/3b0393d5535261f21662fa4b055160dc08b39085)
- [Add background blur to i18n menu](https://github.com/nunocoracao/blowfish/commit/4748453ea3b0adbfd816cc986e6ae8026ae154d7)
Before:
After:
> 🐛 2 Small fixes

- config/_default/params.toml
- exampleSite/config/_default/params.toml
- layouts/partials/analytics/main.html
- layouts/partials/analytics/umami.html
support [umami](https://github.com/umami-software/umami)
https://github.com/nunocoracao/blowfish/issues/933
> ✨ Support Umami Analytics

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/youtubeLite.html
https://github.com/paulirish/lite-youtube-embed?tab=readme-ov-file#custom-player-parameters
> ✨ Add player parameters for youtubeLite shortcode

- exampleSite/content/samples/rich-content/index.ja.md
> 🎏 Update Japanese translation

- exampleSite/content/docs/shortcodes/index.md
> 📚 Remove escape characters in youtubeLite documentation

- i18n/vi.yaml
Changed terms are all in `i18n/vi.yaml`.
> 🌐 Improve Vietnamese translation

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/codeimporter.html
Added a shortcode (modified from mdimporter) for importing code files from external sources.
> ✨ codeimporter shortcode

- exampleSite/content/docs/shortcodes/index.md
- layouts/shortcodes/timeline.html
- layouts/shortcodes/timelineItem.html
Fixes https://github.com/nunocoracao/blowfish/issues/1404
> 🐛 fixed rendering within timeline items

- exampleSite/content/docs/shortcodes/index.md
I made the example code consistent with the given output, in a couple of places.
> Fix inconsistency in docs

- exampleSite/content/users/users.json
Added my portfolio site to the users page.
Thank you for your wonderful work on this theme, @nunocoracao and all its contributors! 💙
> 👤 Add new user to users page

- layouts/partials/footer.html
- package-lock.json
fix https://github.com/nunocoracao/blowfish/issues/1510
> 🐛 fix copyright in footer no longer accepts markdown

- exampleSite/content/docs/getting-started/index.it.md
- exampleSite/content/docs/getting-started/index.ja.md
- exampleSite/content/docs/getting-started/index.md
- exampleSite/content/docs/getting-started/index.zh-cn.md
fix https://github.com/nunocoracao/blowfish/issues/1514
> ✏️ fix https://github.com/nunocoracao/blowfish/issues/1514

- assets/css/compiled/main.css
- layouts/_default/baseof.html
- layouts/partials/toc.html
- package-lock.json
- package.json
- tailwind.config.js
fix https://github.com/nunocoracao/blowfish/issues/1474
> 🎨 Improve UI/UX for long TOCs

- exampleSite/content/docs/configuration/index.it.md
- exampleSite/content/docs/welcome/index.md
- i18n/uk.yaml
I've ported translation from https://github.com/jpanther/congo/pull/703 and adopted to current i18l yaml.
> 🌐 Add Ukrainian translation

- layouts/_default/term.html
- layouts/shortcodes/codeberg.html
should be pretty obvious, please merge
> 🐛 Fix typos

- i18n/ja.yaml
I updated Japanese translation.
> Update Japanese translation

- layouts/partials/meta/date-updated.html
- layouts/partials/meta/date.html
This is my workaround as proposed in #1647.
Additions, hints and corrections are welcome!
> 🐛 workaround for #1647

- exampleSite/content/docs/configuration/index.zh-cn.md
Small typo fix.  It's so small that I don't know whether I should raise this PR. Thank you.
> 🎏  Fix small typo in Chinese doc

- assets/css/compiled/main.css
- assets/css/main.css
- assets/js/mobilemenu.js
- layouts/partials/head.html
- layouts/partials/header/basic.html
fix https://github.com/nunocoracao/blowfish/issues/1695
> ✨ Update mobile menu logic to rely on JS

- config/_default/params.toml
- exampleSite/config/_default/params.toml
- exampleSite/content/docs/configuration/index.it.md
- exampleSite/content/docs/configuration/index.ja.md
- exampleSite/content/docs/configuration/index.md
- exampleSite/content/docs/configuration/index.zh-cn.md
- layouts/_default/rss.xml
[rssnext/follow](https://follow.is/)
https://github.com/nunocoracao/blowfish/issues/1817
> ✨ support rssnext/follow to claim feed as your own

- assets/js/zen-mode.js
Support expanding article title in zen mode
> fix: expand article title in zen mode

- exampleSite/content/users/users.json
I added my data at the end of the file.
> Added my website to the users.json file

- exampleSite/content/users/users.json
I added the data of my personal website at the end of the file which is user.json.
Thx for your review.
> Add my (StepaniaH) blog in user.json

- assets/js/appearance.js
Relevant issue: #1900
I add some code to support the day/night mod change for SVG logo. It's based on the issue: #676
> support the day/night mod change for SVG logo

- exampleSite/content/guides/202310-blowfish-tutorial/index.it.md
- exampleSite/content/guides/202310-blowfish-tutorial/index.ja.md
- exampleSite/content/guides/202310-blowfish-tutorial/index.md
- exampleSite/content/guides/202310-blowfish-tutorial/index.zh-cn.md
- exampleSite/content/samples/external/index.it.md
- exampleSite/content/samples/external/index.ja.md
- exampleSite/content/samples/external/index.md
- exampleSite/content/samples/external/index.zh-cn.md
- package.json
- theme.toml
Replace all nunocoracao.com to n9o.xyz except for the LICENSE file.
> ✏️ Update owner URL to n9o

- assets/js/zen-mode.js
- layouts/_default/single.html
Re Issue #1663
Fix for article footer border line not expanding when in zen mode
> :bug:Fix zen mode footer line bug

- assets/js/zen-mode.js
- layouts/_default/single.html
Reverts nunocoracao/blowfish#2001
> Revert ":bug:Fix zen mode footer line bug"

- assets/css/compiled/main.css
- assets/css/main.css
- exampleSite/content/_index.it.md
- exampleSite/content/_index.ja.md
- exampleSite/content/_index.md
- exampleSite/content/_index.zh-cn.md
- exampleSite/content/docs/firebase-views/index.it.md
- exampleSite/content/docs/firebase-views/index.ja.md
- exampleSite/content/docs/firebase-views/index.md
- exampleSite/content/docs/firebase-views/index.zh-cn.md
1. `npx blowfish-tools` should be in shell language, and Hugo does not support Node.js either.
2. Add the missing language identifier.
> 📝 Docs: update codeblock language

- layouts/shortcodes/gallery.html
> ✨ Feat: gallery shortcode supports all kinds of input

- exampleSite/content/docs/welcome/index.it.md
- exampleSite/content/docs/welcome/index.ja.md
- exampleSite/content/docs/welcome/index.md
- exampleSite/content/docs/welcome/index.zh-cn.md
Update documentation for #2159
> 📝 docs: update documentation for render-image fix

- layouts/_default/_markup/render-image.html
Encapsulates functions to make it more easier to read. This refactor is based on the fix in #2159
> ♻️ Refactor: encapsulates functions in render-image.html

- layouts/shortcodes/article.html
> 🐛 fix: article shortcode across languages (#2130)

- config/_default/params.toml
- exampleSite/config/_default/params.toml
- exampleSite/content/docs/configuration/index.it.md
- exampleSite/content/docs/configuration/index.ja.md
- exampleSite/content/docs/configuration/index.md
- exampleSite/content/docs/configuration/index.zh-cn.md
- exampleSite/layouts/partials/home/custom.html
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/_default/term.html
- layouts/_default/terms.html
- layouts/partials/footer.html
- layouts/partials/head.html
- layouts/partials/meta/zen-mode.html
- layouts/partials/vendor.html
This parameter allows users to choose their algorithm for html integrity checks. This mainly affects Hugo's fingerprint
> 🔒 Add config parameter fingerprintAlgorithm

- exampleSite/content/docs/partials/index.it.md
- exampleSite/content/docs/partials/index.ja.md
- exampleSite/content/docs/partials/index.md
- exampleSite/content/docs/partials/index.zh-cn.md
> 📝 Docs: add docs for uncached head

- assets/icons/worktree.svg
- exampleSite/content/samples/icons/index.it.md
- exampleSite/content/samples/icons/index.md
[worktree.ca](https://worktree.ca/) is a Gitea instance in Canada.
> Add icon for worktree.ca

- .prettierignore
- layouts/partials/head.html
Based on #2239, run prettier format and manually add some empty lines on head.html.
This PR performs the same task as #2180.
(Note: The force push is due to the base changing from main to dev)
> 🎨 Style(head): format head.html

- assets/css/compiled/main.css
- assets/css/main.css
> 🐛 Fix: right margin not blurred in firefox

- assets/css/compiled/main.css
- layouts/partials/series/series-closed.html
- layouts/partials/series/series.html
> 🐛 Fix: serise is too wide

- assets/css/compiled/main.css
- assets/css/main.css
- layouts/partials/article-link/_shortcode.html
- layouts/partials/article-link/card-related.html
- layouts/partials/article-link/card.html
- layouts/partials/article-link/simple.html
This addresses all issues mentioned in: https://github.com/nunocoracao/blowfish/pull/2252#issuecomment-3084947371
@nunocoracao please merge this before publishing the next release. Thanks in advance!
:warning: There are probably merge conflicts with https://github.com/nunocoracao/blowfish/pull/2352 . To fix without me just merge this first and then merge only the change to `$target` from https://github.com/nunocoracao/blowfish/pull/2352
> :ambulance: Hotfix for issues in #2252

- assets/js/fetch-repo.js
> 🐛 Fix: forgejo CORS

- layouts/partials/head.html
ADD adsbygoogle.js IN head.html
> Support google adsense

- .github/ISSUE_TEMPLATE/01-bug-report.yml
Prevent unnecessary bug reports like #2425
Closes #2444
> 🔧 Chore: add Hugo version check to bug report
